UP  add volume 5			#方向键上 音量+5
DOWN  add volume -5		#方向键下 音量-5
ALT+z      no-osd cycle-values osd-level 3 1
KP_ENTER cycle fullscreen
ESC set fullscreen no
Ctrl+d script-message open_search_danmaku_menu
j script-message show_danmaku_keyboard
Ctrl+u script-message check-update
# 核心：单击鼠标左键 = 切换暂停/播放
MBTN_LEFT  cycle pause
# 双击鼠标左键 = 全屏（保留常规操作）
MBTN_LEFT_DBL  cycle fullscreen