
osc = no
# 跳过片头片尾设置 --start=+120 # 从开始后120秒播放 || --end=-40 # 到结尾前40秒时退出
# start = +120 # 从开始后120秒播放
# --end = -100 # 到结尾前40秒时退出

border = no
osd-level = 1 # osd显示等级（osd-status-msg），1仅状态改变显示、3全部显示
# 显示百分比：${time-pos}/${duration}${?percent-pos:(${percent-pos}%)}'
osd-status-msg = ${time-pos}/${duration}\n🕒 ${clock}  # 显示播放时间和系统时间
osd-font-size = 10
osd-align-x = right
osd-bar = no
osd-border-size = 1
# sub-ass-override = strip # 控制字幕是否应该应用用户风格覆盖。
osd-outline-size = 0
osd-bold = yes
sub-color = '#dadee3'
sub-font-size = 36
volume-max = 100
# ========== 强制 HDR 核心（根据自己需求打开） ==========
# vo=gpu-next
# gpu-api=d3d11
# hwdec=auto-safe
# target-colorspace-hint=yes
# hdr-force-output=yes
# target-prim=bt.2020
# target-trc=pq
# hdr-compute-peak=auto
# tone-mapping=hable
# tone-mapping-mode=rgb

# ========== 色彩优化 ==========
# contrast=10
# saturation=8
# brightness=0

# ========== 自动加载 ==========
sub-auto = fuzzy
audio-file-auto = fuzzy

# ========== 提速必关 ==========
icc-profile-auto = no
# ==========================
save-position-on-quit = yes
video-sync=display-resample
