
osc = no

# Editor

# 跳过片头片尾设置 --start=+120 # 从开始后120秒播放 || --end=-40 # 到结尾前40秒时退出
# start = +187 # 从开始后120秒播放
# --end = -100 # 到结尾前40秒时退出

osd-bar-border-size = 0.3
sub-border-color = '#FF303030'
secondary-sub-ass-override = yes

border = no
autofit-larger = 70
loop-playlist = inf
hr-seek-framedrop = no
interpolation = yes
ao = wasapi
volume = 100
audio-file-auto = fuzzy
sub-auto = fuzzy
osd-bar-w = 100
osd-bar-h = 2
osd-bar-align-y = -1
osd-border-size = 1
osd-font-size = 10
osd-on-seek = msg-bar

# 我的自定义
save-position-on-quit = yes
resume-playback-check-mtime = yes
osd-align-x = right
osd-on-seek = msg
osd-bar = yes

# 0:OSD被完全禁用（仅剩字幕）1:启用（仅在用户交互时显示）2:启用 + 默认可见当前时间 3:启用 + --osd-status-msg （默认为当前时间和状态）
osd-level = 1

# 显示百分比：${time-pos}/${duration}${?percent-pos:(${percent-pos}%)}'
osd-status-msg = ${time-pos}/${duration}

osd-outline-size = 0
osd-bold = yes
autofit = 50

sub-ass-override = strip # 控制是否应该应用用户风格覆盖。

icc-profile-auto = no
sub-color = '#FFBFBFBF'
sub-font-size = 36
volume-max = 100
