UP  add volume 5			#方向键上 音量+5
DOWN  add volume -5		#方向键下 音量-5
ALT+z      no-osd cycle-values osd-level 3 1
KP_ENTER cycle fullscreen
ESC set fullscreen no
#字幕搜素
Alt+f   script-message-to  sub_assrt sub-assrt
# 弹幕相关
Ctrl+d script-message open_search_danmaku_menu # 搜索弹幕
d script-message show_danmaku_keyboard # 显示隐藏弹幕
Alt+d script-message open_add_total_menu # 打开弹幕总开关菜单