UP  add volume 5			#方向键上 音量+5
DOWN  add volume -5		#方向键下 音量-5
ALT+z      no-osd cycle-values osd-level 3 1
KP_ENTER cycle fullscreen
ESC set fullscreen no
#字幕搜素
Alt+f   script-message-to  sub_assrt sub-assrt